import { createHash } from "node:crypto";
import { db } from "./index";
import { exercise } from "./schema";

type MuscleGroupBodybuilding = "chest" | "back" | "shoulders" | "arms" | "legs" | "core";
type MuscleGroupMovement = "push" | "pull" | "squat" | "hinge" | "carry";

// Create deterministic UUID from exercise name for idempotency
// Generates a valid UUID v5 format by setting the version and variant bits
function deterministicUUID(name: string): string {
  const hash = createHash("md5").update(name).digest("hex");

  // Split the hash into UUID segments
  const segment1 = hash.slice(0, 8);
  const segment2 = hash.slice(8, 12);
  let segment3 = hash.slice(12, 16);
  let segment4 = hash.slice(16, 20);
  const segment5 = hash.slice(20, 32);

  // Set version to 5 (UUID v5): replace first character of segment3
  segment3 = '5' + segment3.slice(1);

  // Set variant bits (10xx): ensure first character of segment4 is 8, 9, a, or b
  const firstChar = parseInt(segment4[0], 16);
  const variantChar = (8 + (firstChar % 4)).toString(16); // Ensures 8, 9, a, or b
  segment4 = variantChar + segment4.slice(1);

  return `${segment1}-${segment2}-${segment3}-${segment4}-${segment5}`;
}

const SEED_EXERCISES = [
  // Chest (8 exercises)
  {
    name: "Barbell Bench Press",
    category: "chest" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["chest", "shoulders", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Incline Barbell Bench Press",
    category: "chest" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["chest", "shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Dumbbell Bench Press",
    category: "chest" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["chest", "shoulders", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Incline Dumbbell Press",
    category: "chest" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["chest", "shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Cable Fly",
    category: "chest" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["chest"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Chest Dip",
    category: "chest" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["chest", "shoulders", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Push-Up",
    category: "chest" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["chest", "shoulders", "arms", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Dumbbell Fly",
    category: "chest" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["chest"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Back (8 exercises)
  {
    name: "Barbell Row",
    category: "back" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["back", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Pull-Up",
    category: "back" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["back", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Lat Pulldown",
    category: "back" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["back", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Seated Cable Row",
    category: "back" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["back", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Dumbbell Row",
    category: "back" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["back", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "T-Bar Row",
    category: "back" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["back", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Face Pull",
    category: "back" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["back", "shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Chin-Up",
    category: "back" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["back", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Shoulders (7 exercises)
  {
    name: "Overhead Press",
    category: "shoulders" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["shoulders", "arms", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Dumbbell Shoulder Press",
    category: "shoulders" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["shoulders", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Lateral Raise",
    category: "shoulders" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Front Raise",
    category: "shoulders" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Reverse Fly",
    category: "shoulders" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["shoulders", "back"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Arnold Press",
    category: "shoulders" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["shoulders", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Upright Row",
    category: "shoulders" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["shoulders", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Arms (8 exercises)
  {
    name: "Barbell Curl",
    category: "arms" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Dumbbell Curl",
    category: "arms" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Hammer Curl",
    category: "arms" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Tricep Pushdown",
    category: "arms" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Skull Crusher",
    category: "arms" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Overhead Tricep Extension",
    category: "arms" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Preacher Curl",
    category: "arms" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Dip",
    category: "arms" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["arms", "chest", "shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Legs (10 exercises)
  {
    name: "Barbell Squat",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Front Squat",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Leg Press",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Romanian Deadlift",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "back", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["hinge"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Leg Curl",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Leg Extension",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Bulgarian Split Squat",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Calf Raise",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Hip Thrust",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["hinge"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Goblet Squat",
    category: "legs" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Core (5 exercises)
  {
    name: "Plank",
    category: "core" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Hanging Leg Raise",
    category: "core" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Cable Crunch",
    category: "core" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Ab Wheel Rollout",
    category: "core" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Russian Twist",
    category: "core" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Compound / Full Body (5 exercises)
  {
    name: "Deadlift",
    category: "other" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["back", "legs", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["hinge"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Power Clean",
    category: "other" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "back", "shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull", "squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Clean and Jerk",
    category: "other" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "back", "shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull", "squat", "push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Snatch",
    category: "other" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["legs", "back", "shoulders"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull", "squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Farmer's Walk",
    category: "other" as const,
    exerciseType: "weightlifting" as const,
    muscleGroupsBodybuilding: ["arms", "shoulders", "core", "legs"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["carry"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Cardio (6 exercises)
  {
    name: "Running",
    category: "cardio" as const,
    exerciseType: "cardio" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Cycling",
    category: "cardio" as const,
    exerciseType: "cardio" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Rowing",
    category: "cardio" as const,
    exerciseType: "cardio" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Swimming",
    category: "cardio" as const,
    exerciseType: "cardio" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Jump Rope",
    category: "cardio" as const,
    exerciseType: "cardio" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Elliptical",
    category: "cardio" as const,
    exerciseType: "cardio" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Calisthenics (5 exercises)
  {
    name: "Muscle-Up",
    category: "other" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["back", "chest", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["pull", "push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Pistol Squat",
    category: "legs" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["legs", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Handstand Push-Up",
    category: "shoulders" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["shoulders", "arms", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "L-Sit",
    category: "core" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["core", "arms"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Bodyweight Squat",
    category: "legs" as const,
    exerciseType: "calisthenics" as const,
    muscleGroupsBodybuilding: ["legs"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // HIIT (5 exercises)
  {
    name: "Burpees",
    category: "other" as const,
    exerciseType: "hiit" as const,
    muscleGroupsBodybuilding: ["chest", "legs", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["push", "squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Mountain Climbers",
    category: "core" as const,
    exerciseType: "hiit" as const,
    muscleGroupsBodybuilding: ["core", "legs"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Box Jumps",
    category: "legs" as const,
    exerciseType: "hiit" as const,
    muscleGroupsBodybuilding: ["legs"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["squat"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Kettlebell Swings",
    category: "other" as const,
    exerciseType: "hiit" as const,
    muscleGroupsBodybuilding: ["legs", "back", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: ["hinge"] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Battle Ropes",
    category: "other" as const,
    exerciseType: "hiit" as const,
    muscleGroupsBodybuilding: ["arms", "shoulders", "core"] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Yoga/Flexibility (3 exercises)
  {
    name: "Vinyasa Flow",
    category: "other" as const,
    exerciseType: "yoga" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Hatha Yoga",
    category: "other" as const,
    exerciseType: "yoga" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Stretching Routine",
    category: "other" as const,
    exerciseType: "yoga" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },

  // Sports (3 exercises)
  {
    name: "Basketball",
    category: "other" as const,
    exerciseType: "sports" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Tennis",
    category: "other" as const,
    exerciseType: "sports" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
  {
    name: "Hiking",
    category: "other" as const,
    exerciseType: "sports" as const,
    muscleGroupsBodybuilding: [] as MuscleGroupBodybuilding[],
    muscleGroupsMovement: [] as MuscleGroupMovement[],
    isCustom: false,
    createdByUserId: null,
  },
];

async function seed() {
  console.log("Seeding exercises...");
  const exercisesWithIds = SEED_EXERCISES.map((ex) => ({
    ...ex,
    id: deterministicUUID(ex.name),
  }));
  await db.insert(exercise).values(exercisesWithIds).onConflictDoNothing();
  console.log(`Seeded ${SEED_EXERCISES.length} exercises`);
}

seed()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
