/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as ImportIndexRouteImport } from './routes/import/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts/new'
import { Route as WorkoutsWorkoutIdRouteImport } from './routes/workouts/$workoutId'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as ImportWhoopRouteImport } from './routes/import/whoop'
import { Route as AdminExercisesIndexRouteImport } from './routes/admin/exercises/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportIndexRoute = ImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/workouts/new',
  path: '/workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportWhoopRoute = ImportWhoopRouteImport.update({
  id: '/import/whoop',
  path: '/import/whoop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExercisesIndexRoute = AdminExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/import/whoop': typeof ImportWhoopRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/import/': typeof ImportIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/admin/exercises/': typeof AdminExercisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/import/whoop': typeof ImportWhoopRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/admin': typeof AdminIndexRoute
  '/import': typeof ImportIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/admin/exercises': typeof AdminExercisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/import/whoop': typeof ImportWhoopRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/import/': typeof ImportIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/admin/exercises/': typeof AdminExercisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/import/whoop'
    | '/templates/$templateId'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/admin/'
    | '/import/'
    | '/templates/'
    | '/workouts/'
    | '/admin/exercises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/import/whoop'
    | '/templates/$templateId'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/admin'
    | '/import'
    | '/templates'
    | '/workouts'
    | '/admin/exercises'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/import/whoop'
    | '/templates/$templateId'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/admin/'
    | '/import/'
    | '/templates/'
    | '/workouts/'
    | '/admin/exercises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  ImportWhoopRoute: typeof ImportWhoopRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  ImportIndexRoute: typeof ImportIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/': {
      id: '/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/whoop': {
      id: '/import/whoop'
      path: '/import/whoop'
      fullPath: '/import/whoop'
      preLoaderRoute: typeof ImportWhoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exercises/': {
      id: '/admin/exercises/'
      path: '/exercises'
      fullPath: '/admin/exercises/'
      preLoaderRoute: typeof AdminExercisesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminExercisesIndexRoute: typeof AdminExercisesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminExercisesIndexRoute: AdminExercisesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  ImportWhoopRoute: ImportWhoopRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  ImportIndexRoute: ImportIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
