/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts/new'
import { Route as WorkoutsWorkoutIdRouteImport } from './routes/workouts/$workoutId'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/workouts/new',
  path: '/workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/templates/': typeof TemplatesIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/templates': typeof TemplatesIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/templates/': typeof TemplatesIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/templates/$templateId'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/templates/'
    | '/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/templates/$templateId'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/templates'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/templates/$templateId'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/templates/'
    | '/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
